### ISSUE TITLE
Nie można pobrać audycji

### ISSUE THREAD

**Issue by fenuks** [bohdanbobrowski/pr-dl#3]
Dzień dobry,
ostatnia wersja nie potrafi pobrać https://www.polskieradio.pl/7/6149. Pobierane pliki są niezwiązane z tą audycją.

Ponadto, zauważyłem dwa mniejsze problemy: setup.py nie wymienia `lxml` jako zależności i zdaje się, że brakuje pliku prdl/polskieradio_logo_cover.jpg w źródłach.

**Comment by bohdanbobrowski** [comment]
Dzień dobry!
Dzięki za feedback.

Wrzuciłem poprawkę która uwzględnia:
- support dla stron z podcastami o strukturze HTML zbliżonej jak  https://www.polskieradio.pl/7/6149
- uzupełniłem requirements'y w paczce,
- dodałem też brakujący plik.

Będę wdzięczny za gwiazdeczkę i sprawdzenie nowej wersji.

Pozdrawiam.
B.

**Comment by fenuks** [comment]
Dzień dobry,
dziękuję za dodanie wsparcia dla tego typu audycji. Potwierdzam, że działa. Jedynym problemem jest to, że nie są pobierane kolejne strony, które niestety są ładowane przy pomocy javascript i nie można przejść do kolejnej strony, zmieniając adres URL.

**Comment by bohdanbobrowski** [comment]
Walczyłem już z tą paginacją, niestety:
- aby odczytać kolejną stronę trzeba wykonać request POST,
- w tym requeście musi być cała chmara parametrów, nie tylko numer strony
